import React from 'react';
 
const terms = () => {
    return (
        <div className='container' style={{textAlign: 'justify'}}>
       <h1>Terms & Conditions</h1>
<p>By using Creditsin.com products, software, services and web sites (referred to collectively as the "Services"), you understand and agree that Creditsin.com will treat your use of the Services as acceptance of these terms and conditions ("Terms") from that point onwards. "Creditsin.com". In order to use the Services, you must first agree to the Terms. You may not use the Services if you do not accept the Terms. "Website" refers to all Creditsin`s web sites.</p>
<p>You may only use the Website to search for and to apply or refer to friends and family members for loans and credit cards you may not use the Website to make any fraudulent applications. You agree not to use the Website for any purpose that is unlawful, illegal or forbidden by these Terms, or any local laws that might apply to you. We are running the Website in India, so remember that by using the Website, we need you to agree to comply with laws that apply to India and your own country, including laws that apply to exporting technical data.</p>
<p>We may, at our sole discretion, at any time and without advance notice or liability can change the website design, `products & Services` and we may include or exclude one or more financial institutions.</p>
<p>The usage of the website by you, or anyone using your password and login information, for searching the range of products is sole responsibility of you and only you.</p>
<p>The Website is intended for personal, non-commercial use only where in a registered member who is, a major as per law can enter into the binding contract. The sharing of password and using the site for unlawful practices are punishable as per the law.</p>
<p>We may, at our sole discretion, at any time and without advance notice or liability, suspend, terminate or restrict your access to all or any component of the Website.</p>
<p>By using the Website, you provide consent to use your information as we outlined in our Privacy policy.</p>
<p>Creditsin`s display on or through the website for any of the product options offered by third parties does not in any way imply, suggest, or constitute any sponsorship or approval of Creditsin by any such third parties. Creditsin`s display of specific options does not suggest a recommendation by Creditsin of the third parties or their loan, insurance or credit card products. You agree that Creditsin is in no way responsible for the accuracy, timeliness or completeness of information it may obtain from these third parties. Your interaction with any third party accessed through the Website is at your own risk, and Creditsin will have no liability with respect to the acts, omissions, errors, representations, warranties, breaches or negligence of any such third parties or for any personal injuries, death, property damage, or other damages or expenses resulting from your interactions with the third parties.</p>
<p>Creditsin makes no warranty, and expressly disclaims any obligation, that: (a) the content will be up-to-date, complete, comprehensive, accurate or applicable to your circumstances. The website will meet all your requirements and services on and as is and as available basis.</p>
<p>Creditsin expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose, title, non-infringement, and security and accuracy, as well as all warranties arising by usage of trade, course of dealing or course of performance. The website does not make any warranty, and expressly disclaims any obligation, that: <br/></p>
(a) The Website will meet your requirements or will be available on an uninterrupted, timely, secure, or error-free basis; <br/>
(b) the results that may be obtained from the use of the Website or any services offered through the site will be accurate or reliable; or<br/>
(c) the quality of any products, services, information, or other material obtained by you through the site will meet your expectations. <br/>
(d)Creditsin and its proprietor, employees, associates and directors will not hold any responsibility <br/>
A) The performance or non-performance of us or any provider/or not assessable to the content of the website.<br/>
B) Any damages to your computer while access /downloading any content from the website.<br/>
<p>Any loss or death claim, act of god, accident, delay, or any direct, special, exemplary, punitive, indirect, incidental or consequential damages of any kind (including without limitation lost profits or lost savings), whether based in contract, tort, strict liability or otherwise, that arise out of or is in any way connected with .</p>
<p>You agree that you have taken all reasonable precautions to ensure that any data you submit to the Websites is true and accurate. You agree that all information provided on registration on the Websites and otherwise provided by you on this site shall be true, complete and accurate.</p>
<p>All the intellectual property rights ,legal rights ,title and interest is the You acknowledge and agree that Creditsin.com owns all legal rights, title and interest in and to the Services lies with /Creditsin.com only .You further acknowledge that the information, contents shall not be disclosed nor modified without prior written consent of Creditsin.com. You are not authorised to use any of Creditins.com in trade names, trademarks, service marks, logos, domain names, and other distinctive brand feature nor have the right to remove, alter, transmit of obscure any of the trademarks and copyright notices.</p>
<p>Creditsin provide users with a comparison of the key features, fees and rates of different financial products from different financial institutions in India. We are not a finance provider by our own or we are in the process of assisting trying in the application process for a specific financial product of a particular company or issuer. Creditin.com as per clients/customers interest and consent will forward the loans/credit cards/investments etc application to the financial institutions(Banks/NBFC’s) where they will process your application. If the user has the need for further information on any of the products showcased in this site, it is recommended that the user undertake the consult directly from the financial institution. However the updates from the financial institution/s will be communicated to the customers periodically or as and when received. While we endeavour to provide accurate information, this website does not guarantee that the information are always current and accurate,any changes will be updated from time to time.</p>

<p>CREDITSIN  may either directly or in partnership with its Commercial Partners run limited time offers allowing Users to win cashback or other benefits on APP / website offers only those who had taken benefit/or services from APP / Website they only eligible for these benefits or cashback. CREDITSIN reserves the right to introduce, withdraw or vary the terms of such offers from time to time. Any cashbacks advertised or displayed on the CREDITSIN App/Website or through other media channels shall be indicative and the cash back may be of the advertised amount or lesser. Any advertisement or cash back amount displayed on the CREDITSIN App/website shall be deemed to be offering the winners cashback ‘up to’ such amount regardless of whether the word up to is used in such advertisement, display or marketing material on any channel.</p>
<p>You hereby agree to comply with any and all applicable tax laws in connection with your use of the CREDITSIN Services, including without limitation, the reporting and payment of any taxes arising in connection with payments made through the CREDITSIN App, or funds/income received through the CREDITSIN Services.  You hereby agree and acknowledge that if and when required by applicable law, CREDITSIN, may deduct tax deducted at source from your winnings/ cashback and/or may require You to submit PAN details before providing you cashback or other winnings.</p>

<p>You acknowledge that it is your duty to ensure compliance with the terms and conditions described in this T&U Policy and accord your consent to not using the Services and the Online Platforms in any manner which results in committing/attempting to commit any criminal offences. You also agree and consent to any changes made to this Privacy Policy in due course and without notice. You must ensure that any personal information and/or Identification Documents submitted by you belong to you only. In case you are acting on behalf of a juridical person, you must identify the Beneficial Owner and also assist in verification of the identity of such Beneficial Owner and any individual who purports to act on behalf of such juridical person.</p>
<p>In order to mitigate its risks relating to money laundering and other illegal activities, the Company intends to put in place this policy which has the following elements:</p>
•	- Customer Acceptance Terms; and<br/>
•	- Customer Verification Procedure; and<br/>
•	- Transaction Monitoring Terms; and<br/>
•	- Customer Acceptance of using App/ Website.<br/>

<p>Any terms and conditions are subject to modification from time to time and will be intimated prior to 10 days before the change. If you object to these Terms or any subsequent modifications to these Terms or become dissatisfied with the Website in any way, your only recourse is to immediately terminate use of the Website. Other terms and conditions apply as per the product feature.</p>
<p>You acknowledge that you agree to the terms and conditions of the products and as well as the Creditsin.</p>
<p>Any conflict /disagreement of consent or rules are subjected to the jurisdiction of Bangalore Only. You acknowledge that you have read and have understood these Terms, and that these Terms have the same force and effect as a signed agreement.</p>
<p>We advise to the customers before signing the loan agreement go through it and don`t handover blank cheques to associates or executives ( please fill the cheque, payee name [ Bank Name ] & cross cheque is advisable).</p>
<p>Your ideas are solicited and please feel free to share with us for us to serve better. We will assume no responsibility for reviewing unsolicited ideas and will not incur any liability as a result of any similarities between those ideas and materials that may appear in future Creditsin programs. You are requested not to reveal confidential information in your messages to Creditsin and all rights to materials submitted to us become the exclusive property of Creditsin. You are also requested not to hand over any cheque/cash or consideration to any of the associates or Executive.Anybody found doing this act is solely responsible. Creditsin will not entertain any claims as such what so ever.</p>

www.Creditsin.com is not a lender and does not provide loans independently, the company is by no means, assuring as to the correctness of the information, FAQ’s, graphics, images, text and/or various tools and calculators, including their result, displayed at this website or sent to the user by email or otherwise ( together called “information”).  These are purely for indicative purposes and cannot be relied upon, either individually or together with any other information. By the user in any manner whatsoever. The outcome of your case or query or application is solely a matter between you, the lender(s) and/or the applicable regulator, and www.creditsin.com. In does not assure any specific outcome or and outcome. Services or information at this website is for use by Indian national(s) only.


</div>
        
    )
}
 
export default terms;

