export {
  service,
  Updateservice,
  Deleteservice,
  AllService,
  createBank,
  AllBank,
  UpdateBanks,
  DeleteBank,
  AllBankOffer,
  saveBankOffer,
  Applications,
  ApplicationsStateChange,
  allortCashback,
  getTransactionList,
  getUserBankDetailsList,
  ChangeServiceStatus,
  ChangeOfferStatus,
  AllCategory,
  ChangeBankStatus,
  getAllWishList,
  getAllWithDrawls,
  WithDrawlsStateChange,
  WithDrawlsUpdateTransaction,
  DeleteBankOffer,
  BankOfferTextEditor,
  OfferNotifiactionSave
} from './admin.services';

export {
  AllUsers,
  AllRefrals,
  Products,
  AdminLogin,
  ChangeStatus,
  getAllUserEmis,
  getSettingList,
  UpdateSettingList,
  addLoan,
  addInsurance,
  addCreditCard,
  ProductStateChange,
  getAdmins,
  AddAdmin,
  UpdateSubAdmin,
  DeleteSubAdmin
} from './admin.user';
