export const SET_APPLICATIONS  = "SET_APPLICATIONS";
export const SET_APPROVE_APPLICATIONS  = "SET_APPROVE_APPLICATIONS";
export const SET_PENDING_APPLICATIONS  = "SET_PENDING_APPLICATIONS";
export const SET_REJECT_APPLICATIONS  = "SET_REJECT_APPLICATIONS";